### ISSUE TITLE
NoneType has no attribute group

### ISSUE THREAD

**Issue by BlazeFrag** [kenpb/coinbrawl_bot#2]
C:\Python27>python ./coinbrawl_bot.py -f defense
INFO:bot_logic:Starting login process...
INFO:bot_logic:Requesting login page...
INFO:bot_logic:Grabbing authenticity token...
INFO:bot_logic:Login into the site...
INFO:bot_logic:Login succesufully...
INFO:bot_logic:Grabbing arena token...
Traceback (most recent call last):
  File "./coinbrawl_bot.py", line 144, in <module>
    main()
  File "./coinbrawl_bot.py", line 83, in main
    coinBrawl = setup_robot()
  File "./coinbrawl_bot.py", line 52, in setup_robot
    coinBrawl.auth()
  File "C:\Python27\bot_logic.py", line 61, in auth
    self.arena_token = search(arena_token_regex, auth_request.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by BlazeFrag** [comment]
Caused by using latest python ver.

**Comment by kenpb** [comment]
Hello @BlazeFrag, I'm not able to reproduce this but for the looks of it maybe you ran the bot while there was a site reset?

**Comment by BlazeFrag** [comment]
That _seemed_ to be the problem, works fine now! Thanks for the quick reply!

**Comment by kenpb** [comment]
No problem! Glad you have it working.
